/**
 * Resend email integration for transactional emails.
 *
 * Used for:
 * - Welcome email on signup
 * - Weekly digest delivery
 * - Subscription confirmations
 * - Meeting summary shares (viral loop)
 */

export class ResendClient {
  private apiKey: string;
  private fromAddress: string;
  private enabled: boolean;

  constructor(options?: { apiKey?: string; from?: string }) {
    this.apiKey = options?.apiKey ?? process.env.RESEND_API_KEY ?? "";
    this.fromAddress = options?.from ?? "SHOGUN <noreply@syogun.com>";
    this.enabled = Boolean(this.apiKey);
  }

  async send(options: {
    to: string;
    subject: string;
    html: string;
    text?: string;
  }): Promise<boolean> {
    if (!this.enabled) return false;

    try {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`,
        },
        body: JSON.stringify({
          from: this.fromAddress,
          to: [options.to],
          subject: options.subject,
          html: options.html,
          text: options.text,
        }),
      });

      return res.ok;
    } catch {
      return false;
    }
  }

  async sendWelcome(email: string, name: string): Promise<boolean> {
    return this.send({
      to: email,
      subject: "Welcome to SHOGUN — The AI that remembers everything",
      html: `
        <div style="font-family: Inter, sans-serif; max-width: 560px; margin: 0 auto; padding: 40px 20px;">
          <h1 style="color: #C9A84C; font-size: 24px;">Welcome to SHOGUN</h1>
          <p>Hi ${name},</p>
          <p>Your AI memory assistant is ready. SHOGUN will capture, structure, and recall everything you see and do — so you never forget anything important.</p>
          <h3>Getting started:</h3>
          <ol>
            <li>Grant Accessibility permission in System Preferences</li>
            <li>Set your API keys in Settings (optional — keyword search works without them)</li>
            <li>Use ⌘K to search your memory anytime</li>
          </ol>
          <p>Your data stays on your device. Always.</p>
          <p style="color: #8A8580; font-size: 13px;">— Team SHOGUN</p>
        </div>
      `,
    });
  }

  async sendWeeklyDigest(email: string, digest: string): Promise<boolean> {
    const date = new Date().toISOString().slice(0, 10);
    return this.send({
      to: email,
      subject: `SHOGUN Weekly Digest — ${date}`,
      html: `
        <div style="font-family: Inter, sans-serif; max-width: 560px; margin: 0 auto; padding: 40px 20px;">
          <h1 style="color: #C9A84C; font-size: 20px;">Weekly Digest</h1>
          <div style="white-space: pre-wrap; line-height: 1.6;">${digest}</div>
          <p style="color: #8A8580; font-size: 13px; margin-top: 32px;">Generated by SHOGUN — The AI that remembers everything.</p>
        </div>
      `,
    });
  }
}
