import { Icon } from "../components/Icon";
import { useLang } from "../lib/i18n";

export function Work() {
  const lang = useLang();
  const docs = [
    { t: "Pricing page draft", tag: "MARKDOWN", src: "Rev-cat chat · Matt 1-on-1", when: "14:08", status: "draft" },
    { t: "Weekly review · Apr 14", tag: "DOC", src: "23 memories · last week", when: "Apr 14", status: "final" },
    { t: "SHOGUN IA v2", tag: "DOC", src: "Matt feedback · Toru review", when: "Apr 16", status: "in-review" },
  ];
  const tasks = [
    { t: "Draft pricing page", src: "From Rev-cat CTO chat · today", due: "due tomorrow", done: true },
    { t: "Follow up with Matt on Q2 roadmap", src: "From All PJ meeting", due: "today 17:00", done: false },
    { t: "Reply to Elevenlabs intro", src: "From Gmail thread", due: "no deadline", done: false },
    { t: "Decide on BYOK vs hosted default", src: "Open since Apr 10", due: "flagged 3x", done: false },
  ];

  return (
    <div className="content-inner">
      <div className="page-head">
        <div>
          <div className="t-mono" style={{ marginBottom: 8 }}>OPERATIONS LAYER</div>
          <h1>Work <span className="jp">任務</span></h1>
          <div className="sub">{lang === "ja" ? "SHOGUNがメモリから生成したドキュメントとタスク" : "Documents and tasks generated by SHOGUN from your memory. Editable, owned by you."}</div>
        </div>
        <div className="row">
          <button className="btn btn-secondary"><Icon name="filter" size={14} />All types</button>
          <button className="btn btn-primary"><Icon name="plus" size={14} />New document</button>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16, marginBottom: 32 }}>
        {docs.map((d, i) => (
          <div key={i} className="card card-interactive" style={{ padding: 0, overflow: "hidden" }}>
            <div style={{ padding: "14px 18px", background: "var(--surface-2)", borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", gap: 10 }}>
              <Icon name="file" size={14} className="gold" />
              <span className="t-mono" style={{ fontSize: 10 }}>{d.tag}</span>
              <span className="spacer" />
              <span className={d.status === "final" ? "label label-success" : d.status === "draft" ? "label label-gold" : "label"}>{d.status}</span>
            </div>
            <div style={{ padding: 20 }}>
              <div style={{ fontSize: 15, fontWeight: 500, marginBottom: 12 }}>{d.t}</div>
              <div style={{ fontSize: 12, color: "var(--text-dim)", marginBottom: 16 }}>From: {d.src}</div>
              <div className="stack-2">
                <div style={{ height: 6, background: "var(--surface-2)", borderRadius: 3, width: "96%" }} />
                <div style={{ height: 6, background: "var(--surface-2)", borderRadius: 3, width: "82%" }} />
                <div style={{ height: 6, background: "var(--surface-2)", borderRadius: 3, width: "70%" }} />
              </div>
            </div>
            <div style={{ padding: "12px 18px", borderTop: "1px solid var(--border)", display: "flex", alignItems: "center", gap: 10 }}>
              <span className="t-mono" style={{ fontSize: 10 }}>{d.when}</span>
              <span className="spacer" />
              <Icon name="link" size={12} className="dim" />
              <span style={{ fontSize: 11, color: "var(--text-dim)" }}>{i + 3} memories</span>
            </div>
          </div>
        ))}
      </div>

      <div style={{ fontSize: 13, fontWeight: 500, marginBottom: 14, color: "var(--text-mute)" }}>{lang === "ja" ? "タスク · メモリから抽出" : "Tasks · surfaced from memory"}</div>
      <div className="card" style={{ padding: 0 }}>
        {tasks.map((t, i) => (
          <div key={i} className="row" style={{ padding: "14px 20px", borderBottom: i < tasks.length - 1 ? "1px solid var(--border)" : "none", gap: 14 }}>
            <div style={{ width: 16, height: 16, border: "1.5px solid " + (t.done ? "var(--gold)" : "var(--border-hi)"), borderRadius: "var(--radius-sm)", display: "flex", alignItems: "center", justifyContent: "center" }}>
              {t.done && <Icon name="check" size={10} className="gold" />}
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 14 }}>{t.t}</div>
              <div style={{ fontSize: 11, color: "var(--text-dim)", marginTop: 2 }}>{t.src}</div>
            </div>
            <span className="label">{t.due}</span>
            <button className="btn btn-sm btn-ghost"><Icon name="more" size={14} /></button>
          </div>
        ))}
      </div>
    </div>
  );
}
