import type { ShogunBrain } from "../brain.js";
import { logger } from "../logger.js";

/**
 * SHOGUN Viral Loop & Growth Engine
 *
 * 4つのバイラルループ:
 *
 * 1. SHARE MEMORY SNIPPET
 *    「この人こんなこと言ってたよ」→ 共有リンクで相手もSHOGUNに興味
 *    User → generates beautiful memory card → shares on Twitter/Slack → recipient sees SHOGUN branding → signs up
 *
 * 2. MEETING SUMMARY SHARE
 *    会議後の要約を参加者全員に送る → 「これ何で作ったの？」
 *    User finishes meeting → SHOGUN auto-generates summary → user shares with attendees → "What tool is this?" → sign up
 *
 * 3. WEEKLY DIGEST FORWARD
 *    週次ダイジェストを上司/チームに転送 → 「俺もこれ欲しい」
 *    User gets weekly digest → forwards to team → team sees value → team signs up
 *
 * 4. BRAIN SIZE FLEX
 *    「俺のBrainは5000ページ」→ ステータスシンボル化
 *    User sees Brain stats → shares milestone on social media → social proof → sign up
 */

export interface ShareableCard {
  type: "memory_snippet" | "meeting_summary" | "weekly_digest" | "brain_stats";
  title: string;
  content: string;
  metadata: Record<string, unknown>;
  /** Branded share URL */
  shareUrl: string;
  /** Open Graph metadata for social preview */
  ogTitle: string;
  ogDescription: string;
}

export class ViralEngine {
  constructor(private brain: ShogunBrain) {}

  /**
   * Generate a shareable memory snippet card.
   * Includes SHOGUN branding and a "Try SHOGUN" call-to-action.
   */
  async createMemoryCard(slug: string): Promise<ShareableCard | null> {
    const page = await this.brain.pages.getPage(slug);
    if (!page) return null;

    const tags = await this.brain.tags.getTagsForPage(page.id);
    const excerpt = page.compiled_truth.slice(0, 280);

    return {
      type: "memory_snippet",
      title: page.title,
      content: excerpt,
      metadata: { slug, type: page.type, tags },
      shareUrl: `https://syogun.com/shared/${encodeURIComponent(slug)}`,
      ogTitle: `${page.title} — SHOGUN Memory`,
      ogDescription: `${excerpt}... | Powered by SHOGUN — The AI that remembers everything.`,
    };
  }

  /**
   * Generate a meeting summary share card.
   */
  async createMeetingSummaryCard(
    slug: string,
    summary: string
  ): Promise<ShareableCard> {
    return {
      type: "meeting_summary",
      title: `Meeting Summary`,
      content: summary,
      metadata: { slug },
      shareUrl: `https://syogun.com/meeting/${encodeURIComponent(slug)}`,
      ogTitle: "Meeting Summary — SHOGUN",
      ogDescription: `${summary.slice(0, 200)}... | Auto-generated by SHOGUN`,
    };
  }

  /**
   * Generate Brain stats milestone card for social sharing.
   */
  async createBrainStatsCard(): Promise<ShareableCard> {
    const stats = await this.brain.getStats();
    const health = await this.brain.getHealth();

    const milestoneText = getBrainMilestone(stats.total_pages);

    return {
      type: "brain_stats",
      title: milestoneText.title,
      content: milestoneText.content,
      metadata: {
        total_pages: stats.total_pages,
        total_links: stats.total_links,
        embed_coverage: health.embed_coverage,
      },
      shareUrl: "https://syogun.com",
      ogTitle: `${milestoneText.title} — SHOGUN`,
      ogDescription: milestoneText.content,
    };
  }
}

function getBrainMilestone(pages: number): { title: string; content: string } {
  if (pages >= 10000) return {
    title: "🧠 Brain Master",
    content: `My SHOGUN Brain has ${pages.toLocaleString()} memories. The AI that remembers everything. #SHOGUN`,
  };
  if (pages >= 5000) return {
    title: "🧠 Memory Elite",
    content: `${pages.toLocaleString()} memories and growing. SHOGUN never forgets. #SHOGUN`,
  };
  if (pages >= 1000) return {
    title: "🧠 1K Memories!",
    content: `Hit ${pages.toLocaleString()} memories in my SHOGUN Brain! Every conversation, every meeting, every idea — remembered. #SHOGUN`,
  };
  if (pages >= 100) return {
    title: "🧠 Growing Brain",
    content: `${pages} memories captured by SHOGUN. It's like having a second brain that never sleeps. #SHOGUN`,
  };
  return {
    title: "🧠 First Memories",
    content: `Just started building my AI memory with SHOGUN. ${pages} memories and counting. #SHOGUN`,
  };
}

/**
 * Intelligence Score — "使うほど賢くなる" metric.
 *
 * This score increases as the Brain grows and becomes more connected.
 * Displayed to users to create a sense of progress and investment.
 *
 * Components:
 * - Volume: number of pages (logarithmic)
 * - Connectivity: links per page
 * - Coverage: embed coverage
 * - Freshness: recent activity
 * - Diversity: type distribution
 */
export async function calculateIntelligenceScore(brain: ShogunBrain): Promise<{
  score: number; // 0-100
  level: string;
  levelJa: string;
  breakdown: Record<string, number>;
}> {
  const stats = await brain.getStats();
  const health = await brain.getHealth();

  // Volume score (0-25): log scale, caps at 10k pages
  const volumeScore = Math.min(25, Math.log10(Math.max(1, stats.total_pages)) * 10);

  // Connectivity score (0-25): links per page ratio
  const linksPerPage = stats.total_pages > 0 ? stats.total_links / stats.total_pages : 0;
  const connectivityScore = Math.min(25, linksPerPage * 12.5);

  // Coverage score (0-25): embedding coverage
  const coverageScore = health.embed_coverage * 25;

  // Diversity score (0-25): how balanced the type distribution is
  const types = Object.values(stats.pages_by_type);
  const total = types.reduce((a, b) => a + b, 0);
  const entropy = total > 0
    ? -types.reduce((sum, count) => {
        if (count === 0) return sum;
        const p = count / total;
        return sum + p * Math.log2(p);
      }, 0) / 2 // Normalize to 0-1 for 4 types
    : 0;
  const diversityScore = entropy * 25;

  const totalScore = Math.round(volumeScore + connectivityScore + coverageScore + diversityScore);

  const { level, levelJa } = getIntelligenceLevel(totalScore);

  return {
    score: totalScore,
    level,
    levelJa,
    breakdown: {
      volume: Math.round(volumeScore),
      connectivity: Math.round(connectivityScore),
      coverage: Math.round(coverageScore),
      diversity: Math.round(diversityScore),
    },
  };
}

function getIntelligenceLevel(score: number): { level: string; levelJa: string } {
  if (score >= 90) return { level: "Omniscient", levelJa: "全知" };
  if (score >= 75) return { level: "Sage", levelJa: "賢者" };
  if (score >= 60) return { level: "Scholar", levelJa: "学者" };
  if (score >= 40) return { level: "Apprentice", levelJa: "見習い" };
  if (score >= 20) return { level: "Novice", levelJa: "初心者" };
  return { level: "Awakening", levelJa: "覚醒" };
}
